---
title: "Epidemiology: Beyond the Basics"
subtitle: "Moyses Szklo e F. Javier Nieto<br><br>"
author: "**Elaboração:**<br>Denis de Oliveira Rodrigues<br>Doutorando em Epidemiologia em Saúde Pública<br>Escola Nacional de Saúde Pública/Fiocruz"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Table 1-3 on page 8.

```{r}
df_tab_1_3 <-
  tibble::tibble(
    birth_cohort_range = c("1925-1934", "1935–1944", "1945–1954", "1955–1964", "1965–1974"),
    midpoint_cohort = c(1930, 1940, 1950, 1960, 1970),
    age_group_15 = c(NA, NA, NA, 17, 28),
    age_group_25 = c(NA, NA, 14, 23, 35),
    age_group_35 = c(NA, 12, 19, 30, 45),
    age_group_45 = c(10, 18, 26, 40, NA),
    age_group_55 = c(15, 22, 36, NA, NA),
    age_group_65 = c(20, 31, NA, NA, NA),
    age_group_75 = c(27, NA, NA, NA, NA)
  )
```

Tentativa com `flextable`:

```{r}
library(flextable)
# tema
my_theme <- function(x, ...) {
    x <- colformat_double(x, big.mark = "", decimal.mark = ",", digits = 0)
    # x <- colformat_double(x, big.mark = "", decimal.mark = "", digits = 0)
    x <- set_table_properties(x, layout = "fixed")
    x <- border_remove(x)
    std_border <- officer::fp_border(width = 1, color = "white")
    x <- border_outer(x, part="all", border = std_border )
    x <- border_inner_h(x, border = std_border, part="all")
    x <- border_inner_v(x, border = std_border, part="all")
    x <- font(x, fontname = "Myriad Pro", part = "all")
    x <- color(x, color = "white", part = "header")
    x <- bold(x, i = 2:nrow_part(x, "header"), part = "header") 
    x <- fontsize(x, size = 14, part = "all")
    x <- align(x, j = 2:ncol_keys(x), align = "center", part = "all")
    x <- bg(x, i = 1, j = 1, bg = "#6CA439", part = "header")
    x <- bg(x, i = 2:nrow_part(x, "header"), j = 1:ncol_keys(x), bg = "#9ABC85", part = "header")
    x <- bg(x, i = seq_len(nrow_part(x, "body"))%%2!=1, bg = "#E6EDE2", part = "body")
    x <- line_spacing(x, space = 1.5, part = "all")
    x <- padding(x, j = 1, padding = 10, part = "header")
    x <- padding(x, j = 1, padding.left = 10, part = "body")
    # fit_to_width(x, max_width = 8)
    autofit(x)
}

df_tab_1_3 |>
  dplyr::mutate(across(
    .cols = dplyr::starts_with("age_group"),
    .fns = ~ tidyr::replace_na(.x, 0)
  )) |>
  flextable::flextable() |>
  flextable::merge_h_range(j1 = "age_group_15", j2 = "age_group_75", part = "header") |>
  flextable::set_header_labels(values = list(
    "birth_cohort_range" = "Birth cohort range",
    "midpoint_cohort" = "Midpoint",
    "age_group_15" = "Prevalence (per 1000)")) |> 
  flextable::add_header_row(
    values = c("Birth cohort range", "Midpoint", "15", "25", "35", "45", "55", "65", "75"),
    colwidths = rep(1,9)
  ) |> 
  flextable::add_header_row(
    values = c("Birth cohort range", "Midpoint", "Age group (midpoint, in years)"),
    colwidths = c(1,1,7)
  ) |> 
  flextable::merge_v(part = "header") |> 
  flextable::valign(j= 1:2, valign = "bottom", part = "header") |> 
  flextable::add_header_lines("TABLE 1-3\tRearrangement of the data shown in Table 1-2 by birth cohort.") |> 
  my_theme() 


  
  

```


Tentativa falha de reproduzir o identificador *Prevalence (per 1000)*.
<br>

```{r}
df_tab_1_3 |>
  dplyr::mutate(across(
    .cols = dplyr::starts_with("age_group"),
    .fns = ~ tidyr::replace_na(.x, 0)
  )) |>
  gt::gt() |>
  gt::tab_header(title = gt::md(
    "**TABLE 1-3** Rearrangement of the data shown in Table 1-2 by birth cohort."
  ),) |>
  gt::cols_label(
    birth_cohort_range = gt::md("**Birth cohort range**"),
    midpoint_cohort = gt::md("**Midpoint**"),
    age_group_15 = gt::md("**15**"),
    age_group_25 = gt::md("**25**"),
    age_group_35 = gt::md("**35**"),
    age_group_45 = gt::md("**45**"),
    age_group_55 = gt::md("**55**"),
    age_group_65 = gt::md("**65**"),
    age_group_75 = gt::md("**75**")
  ) |>
  gt::cols_align(align = "center",
                 columns = 2:9) |>
  gt::tab_spanner(
    id = "s1",
    label = gt::md("**Age group (midpoint, in years) <br> Prevalence (per 1000)**"),
    columns = 3:9
  ) |>
  
  gt::tab_style(
    style = list(
      gt::cell_fill(color = "#6CA439"),
      gt::cell_text(
        color = "#FFFFFF",
        size = gt::px(19),
        align = "left",
        font = "Myriad Pro"
      )
    ),
    locations = gt::cells_title(groups = "title")
  ) |>
  gt::tab_style(
    style = list(
      gt::cell_fill(color = "#9ABC85"),
      gt::cell_text(color = "#FFFFFF",
                    font = "Myriad Pro")
    ),
    locations = list(gt::cells_column_spanners(),
                     gt::cells_column_labels())
  )  |>
  gt::tab_style(
    style = gt::cell_borders(
      sides = "all",
      color = "#FFFFFF",
      weight = gt::px(2)
    ),
    locations = list(gt::cells_title(groups = "title"),
                     gt::cells_body())
  ) |>
  gt::tab_style(
    style = gt::cell_borders(
      sides = c("left", "right"),
      color = "#FFFFFF",
      weight = gt::px(2)
    ),
    locations = list(gt::cells_column_labels())
  ) |>
  gt::tab_style(style = list(gt::cell_text(size = 14,
                                           font = "Myriad Pro")),
                locations = gt::cells_body())  |>
  gt::tab_style(
    style = gt::cell_borders(
      sides = c("left", "right"),
      color = "#FFFFFF",
      weight = gt::px(2)
    ),
    locations = list(gt::cells_column_spanners("s1"))
  ) |>
  gt::tab_style(
    style = "padding-left:15px",
    locations = list(
      gt::cells_title(groups = "title"),
      gt::cells_column_labels(columns = birth_cohort_range),
      gt::cells_body(columns = birth_cohort_range)
    )
  ) |>
  gt::opt_row_striping() |>
  gt::tab_options(
    heading.padding = gt::px(15),
    table.width = "100%",
    row.striping.include_stub = TRUE,
    row.striping.background_color = "#E6EDE2"
  ) |>
  gt::opt_table_font(font = list("Myriad Pro", "Myriad Pro Condensed"))

```

```{r}
df_tab_1_3_t <- df_tab_1_3 |>
  tidyr::pivot_longer(
    cols = tidyselect::starts_with("age_group_"),
    names_to = "midpoint_age",
    values_to = "prevalence",
    names_prefix = "age_group_",
    names_transform = list(midpoint_age = as.numeric)
  )
```

```{r}
df_tab_1_1_update <- data.frame(
  midpoint_cohort = "2005",
  midpoint_age = c(35, 45, 55, 65, 75),
  prevalence = c(45, 40, 36, 31, 27)
)

```


```{r}
g1 <- df_tab_1_3_t |>
  ggplot2::ggplot(ggplot2::aes(x = midpoint_age,
                               y = prevalence)) +
  ggplot2::geom_point(ggplot2::aes(group = midpoint_cohort),
                      color = "#83AF64",
                      size = 2) +
  ggplot2::geom_line(
    ggplot2::aes(group = midpoint_cohort),
    color = "#83AF64",
    linewidth = .5,
    linetype = 2
  ) +
  ggplot2::geom_line(
    data = df_tab_1_1_update,
    ggplot2::aes(x = midpoint_age, y = prevalence, group = midpoint_cohort),
    color = "#83AF64",
    linewidth = 1
  )+
  ggplot2::annotate(
    "text",
    x = c(17, 28, 38, 48, 58),
    y = c(33, 29, 24, 22, 20),
    label = c("1970", "1960", "1950", "1940", "1930"),
    size = 5,
    angle = c(6, 10, 15, 20, 25),
    family = "Arial"
  ) +
    ggplot2::annotate(
    "text",
    x = c(60),
    y = c(39),
    label = c("2005 cross-sectional\nsurvey"),
    size = 5,
    angle = -29,
    family = "Arial"
  ) +
  ggplot2::scale_x_continuous(
    breaks = seq(0, 80, 10),
    expand = c(0, 0),
    limits = c(0, 83)
  ) +
  ggplot2::scale_y_continuous(expand = c(0, 0), limits = c(0, 53)) +
  ggplot2::labs(x = "Age (years)",
                y = "Prevalence (per 1000)") +
  ggplot2::theme_bw() +
  ggplot2::theme(
    plot.margin = ggplot2::margin(10, 100, 10, 150, unit = "pt"),
    panel.border = ggplot2::element_rect(color = "#83AF64", linewidth = 1.5),
    panel.grid = ggplot2::element_blank(),
    plot.background = ggplot2::element_rect(color = "#83AF64", linewidth = 0.5),
    plot.caption = ggplot2::element_text(hjust = 0, family = "Arial"),
    axis.ticks = ggplot2::element_line(linewidth = 0.5, color = "#83AF64"),
    axis.ticks.length = ggplot2::unit(5, "pt"),
    axis.title = ggplot2::element_text(size = 14, family = "Arial",color = "black"),
    axis.text =  ggplot2::element_text(size = 14, family = "Arial",color = "black"),
  )


my_g <- grid::grobTree(
  grid::rectGrob(
    # width = grid::unit(10, "npc"),
    gp = grid::gpar(
      fill = "#6CA439",
      col = "#9ABC85"
      )
    ),
  # grid::textGrob(
  gridtext::richtext_grob(
    "**FIGURE 1-3** Plotting of the data in Figure 1-2 by birth cohort (see also Table 1-3). The dotted lines represent the different<br>birth cohorts (from 1930 to 1970) as they converge to the 2005 cross-sectional survey (solid line, as in Figure 1-1).",
    x = .03,
    hjust = 0,
    margin = grid::unit(c(0.3, 0.3, 0.3, 0.3), "pt"),
    gp = grid::gpar(col = "#FFFFFF",
                    fontsize = 16,
                    fontfamily = "Myriad Pro")
  )
) |> 
  ggplotify::as.grob()
```

```{r fig.align='center', fig.width=9}
gridExtra::grid.arrange(g1, my_g, heights = c(9, 2))
```

```{r}

g2 <- gridExtra::arrangeGrob(g1, my_g, heights = c(9, 2)) |> ggplotify::as.ggplot()
ggplot2::ggsave("../figure_1_3.png",g2, width = 9, height = 5)

```
