---
title: "Epidemiology: Beyond the Basics"
subtitle: "Moyses Szklo e F. Javier Nieto<br><br>"
author: "**Elaboração:**<br>Denis de Oliveira Rodrigues<br>Doutorando em Epidemiologia em Saúde Pública<br>Escola Nacional de Saúde Pública/Fiocruz"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Página 4 e 5:

```{r}
df_tab_1_1 <- data.frame(age_group = c("30-39","40-49","50-59","60-69","70-79"),
                         midpoint = c(35,45,55,65,75),
                         prevalence_2005 = c(45,40,36,31,27))
```


```{r}
df_tab_1_1 |>
  gt::gt() |>
  gt::tab_header(
    title = gt::md("**TABLE 1-1** Hypothetical data from a cross-sectional study of prevalence of disease Y in a population, by age, 2005."),
  ) |>
  gt::cols_label(
    age_group = gt::md("**Age group (years)**"),
    midpoint = gt::md("**Midpoint (years)**"),
    prevalence_2005 = gt::md("**2005 Prevalence (per 1000)**")
  ) |>
  gt::cols_align(
    align = "center",
    columns = c(midpoint, prevalence_2005)
    ) |>
  gt::tab_style(
    style = list(
      gt::cell_fill(color = "#6CA439"),
      gt::cell_text(color = "#FFFFFF", 
                    size = gt::px(16),
                    align = "left")
    ),
  locations = gt::cells_title(groups = "title")
) |>
  gt::tab_style(
    style = list(
      gt::cell_fill(color = "#9ABC85"),
      gt::cell_text(color = "#FFFFFF")
    ),
  locations = gt::cells_column_labels()
)  |>
  gt::tab_style(
    style = gt::cell_borders(
      sides = "all", 
      color = "#FFFFFF",
      weight = gt::px(2)
      ),
    locations = list(
      gt::cells_title(groups = "title"),
      gt::cells_stubhead(),
      gt::cells_column_labels(),
      gt::cells_body()
    )
  ) |>
  gt::tab_style(
    style = "padding-left:15px",
    locations = list(
      gt::cells_title(groups = "title"),
      gt::cells_column_labels(columns = age_group),
      gt::cells_body(columns = age_group)
    )
  ) |>
  gt::opt_row_striping() |>
  gt::tab_options(
    heading.padding = gt::px(15),
    table.width = "100%",
    row.striping.include_stub = TRUE,
    row.striping.background_color = "#E6EDE2"
    ) |>
  gt::opt_table_font(
    font = list(
      gt::google_font(name = "Roboto Condensed"),
      "Arial Narrow"
    )
  )
 
```


```{r}

g1 <-
  ggplot2::ggplot(data = df_tab_1_1, ggplot2::aes(x = midpoint,
                                                  y = prevalence_2005)) +
    ggplot2::geom_point(color = "#83AF64", size = 2) +
    ggplot2::geom_line(color = "#83AF64", size = 1) +
    ggplot2::scale_x_continuous(breaks = seq(0,80,10), expand = c(0, 0), limits = c(0,83)) +
    ggplot2::scale_y_continuous(expand = c(0, 0), limits = c(0,53)) +
    ggplot2::labs(x = "Age (years)",
                  y = "Prevalence (per 1000)") +
    ggplot2::theme_bw() +
    ggplot2::theme(
      plot.margin = ggplot2::margin(10,100,10,150, unit = "pt"),
      panel.border = ggplot2::element_rect(color = "#83AF64", size = 1.5),
      panel.grid = ggplot2::element_blank(),
      plot.background = ggplot2::element_rect(color = "#83AF64", size = 0.5),
      plot.caption = ggplot2::element_text(hjust = 0),
      axis.ticks = ggplot2::element_line(size = 0.5, color = "#83AF64"),
      axis.ticks.length = ggplot2::unit(5, "pt"),
      axis.title = ggplot2::element_text(size = 14),
      axis.text =  ggplot2::element_text(size = 14),
    )


my_g <- grid::grobTree(
  grid::rectGrob(
    # width = grid::unit(10, "npc"),
    gp = grid::gpar(
      fill = "#6CA439",
      col = "#9ABC85"
      )
    ),
  # grid::textGrob(
  gridtext::richtext_grob(
    "**FIGURE 1-1** Hypothetical data from a cross-sectional study of prevalence of disease Y in a population, by age, 2005<br>(based on data from Table 1-1).",
    x = .05,
    hjust = 0,
    gp = grid::gpar(col = "#FFFFFF",
                    fontsize = 14,
                    fontfamily = "Roboto Condensed")
  )
) |> 
  ggplotify::as.grob()

```


```{r fig.align='center', fig.width=10}
gridExtra::grid.arrange(g1, my_g, heights = c(9, 1.2))
```

